/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/Models/chair1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import state from '@/app/store'
import * as THREE from "three"
export default function Chair1(props) {
  //textures
  const Texture1 = new THREE.TextureLoader().load("../textures/fabric1/fabric_pattern_07_col_1_1k.png")




  const { nodes, materials } = useGLTF('/Models/chair1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Cylinder001_Material_#2146932551_0'].geometry} 
      material={materials.Material_2146932551} 
      material-color = {state.currentColor}
      rotation={[-Math.PI / 2, 0, 0]} scale={[state.width * 0.001, state.thickness * 0.001, state.height * 0.001]} />
    </group>
  )
}

useGLTF.preload('/Models/chair1.glb')

// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.10 public/Models/chair1.glb 
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
// import * as THREE from "three"
// import state from '@/app/store'


// export default function Chair1(props) {
//   const [mapTexture, normalTexture] = ([
//     new THREE.TextureLoader().load("../textures/fabric1/fabric_pattern_07_col_1_1k.png"),
//     new THREE.TextureLoader().load("../textures/fabric1/fabric_pattern_07_nor_gl_1k.exr")
//   ]) 
  
//   const { nodes, materials } = useGLTF('/Models/chair1.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes['Cylinder001_Material_#2146932551_0'].geometry} 
//       material={new THREE.MeshStandardMaterial({map: mapTexture, normalMap:normalTexture})} rotation={[-Math.PI / 2, 0, 0]} 
//       material-color="#f3f3f3"
//       scale={0.001} />
//     </group>
//   )
// }

// useGLTF.preload('/Models/chair1.glb')
