/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/Models/newChair7.glb --transform --shadow, s 
Files: public/Models/newChair7.glb [4.87MB] > newChair7-transformed.glb [884.9KB] (82%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function NewChair7(props) {
  const { nodes, materials } = useGLTF('/Models/newChair7.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_0001.geometry} material={materials.Wood051} />
      <mesh geometry={nodes.Object_0001_1.geometry} material={materials.Leather031} />
    </group>
  )
}

useGLTF.preload('/Models/newChair7.glb')
