/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/Models/table.glb --shadow, s 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import state from '@/app/store'
import * as THREE from "three"

export default function Table(props) {

  //textures
  
  const Texture1 = new THREE.TextureLoader().load("../../textures/wood1/dark_wooden_planks_diff_1k.jpg")
  const Texture2 = new THREE.TextureLoader().load("../../textures/wood2/synthetic_wood_diff_1k.jpg")
  const Texture3 = new THREE.TextureLoader().load("../../textures/wood3/wood_floor_deck_diff_1k.jpg")
  const Texture4 = new THREE.TextureLoader().load("../../textures/wood4/wood_cabinet_worn_long_diff_1k.jpg")
  const Texture5 = new THREE.TextureLoader().load("../../textures/wood5/weathered_planks_diff_1k.jpg")
  const Texture6 = new THREE.TextureLoader().load("../../textures/wood6/weathered_brown_planks_diff_1k.jpg")
  const Texture7 = new THREE.TextureLoader().load("../../textures/wood7/planks_brown_10_diff_1k.jpg")

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Models/table.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model009" rotation={[-Math.PI / 2, 0, 0]} scale={[state.width, state.thickness, state.height]}>
          <group name="table_final_animated_v3fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode005">
                <group name="TableFinalEmpty" position={[-32.203, 73.425, 18.019]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="TableFinalDrawer">
                    <mesh name="TableFinalDrawer_Antique_Table_0" geometry={nodes.TableFinalDrawer_Antique_Table_0.geometry} 
                    material={materials.Antique_Table}
                    material-color = {state.currentColor}
                    position={[32.203, 18.025, -73.425]}
                    castShadow>
                         {state.currentTexture==="Texture1" &&<meshStandardMaterial map={Texture1} roughness={0.8}  />} 
                             {state.currentTexture==="Texture2" &&<meshStandardMaterial map={Texture2} roughness={0.8} />} 
                             {state.currentTexture==="Texture3" &&<meshStandardMaterial map={Texture3} roughness={0.8} />} 
                             {state.currentTexture==="Texture4" &&<meshStandardMaterial map={Texture4} roughness={0.8} />} 
                             {state.currentTexture==="Texture5" &&<meshStandardMaterial map={Texture5} roughness={0.8} />} 
                             {state.currentTexture==="Texture6" &&<meshStandardMaterial map={Texture6} roughness={0.8} />} 
                             {state.currentTexture==="Texture7" &&<meshStandardMaterial map={Texture7} roughness={0.8} />} 
                      </mesh>

                    <group name="TableFinalDrawerHandles" position={[14.616, -4.088, -5.533]}>
                      <mesh name="TableFinalDrawerHandles_Antique_Table_0" 
                      geometry={nodes.TableFinalDrawerHandles_Antique_Table_0.geometry} 
                      material={materials.Antique_Table} position={[17.587, 22.113, -67.892]} >
                          material-color = {state.currentColor}
                        </mesh>
                    </group>
                  </group>
                  <mesh name="TableFinalEmpty_Antique_Table_0"
                   geometry={nodes.TableFinalEmpty_Antique_Table_0.geometry} 
                   material-color = {state.currentColor}
                   material={materials.Antique_Table} position={[32.203, 18.019, -73.425]}
                   >
                         {state.currentTexture==="Texture1" &&<meshStandardMaterial map={Texture1} roughness={0.8}  />} 
                             {state.currentTexture==="Texture2" &&<meshStandardMaterial map={Texture2} roughness={0.8} />} 
                             {state.currentTexture==="Texture3" &&<meshStandardMaterial map={Texture3} roughness={0.8} />} 
                             {state.currentTexture==="Texture4" &&<meshStandardMaterial map={Texture4} roughness={0.8} />} 
                             {state.currentTexture==="Texture5" &&<meshStandardMaterial map={Texture5} roughness={0.8} />} 
                             {state.currentTexture==="Texture6" &&<meshStandardMaterial map={Texture6} roughness={0.8} />} 
                             {state.currentTexture==="Texture7" &&<meshStandardMaterial map={Texture7} roughness={0.8} />} 
                  
                    </mesh>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/table.glb')
