/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/Models/table5.glb --shadow, s 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import state from '@/app/store'
import * as THREE from "three"

export default function Table5(props) {

  const Texture1 = new THREE.TextureLoader().load("../../textures/wood1/dark_wooden_planks_diff_1k.jpg")
  const Texture2 = new THREE.TextureLoader().load("../../textures/wood2/synthetic_wood_diff_1k.jpg")
  const Texture3 = new THREE.TextureLoader().load("../../textures/wood3/wood_floor_deck_diff_1k.jpg")
  const Texture4 = new THREE.TextureLoader().load("../../textures/wood4/wood_cabinet_worn_long_diff_1k.jpg")
  const Texture5 = new THREE.TextureLoader().load("../../textures/wood5/weathered_planks_diff_1k.jpg")
  const Texture6 = new THREE.TextureLoader().load("../../textures/wood6/weathered_brown_planks_diff_1k.jpg")
  const Texture7 = new THREE.TextureLoader().load("../../textures/wood7/planks_brown_10_diff_1k.jpg")


  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Models/table5.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} scale={[state.width * 0.3, state.height * 0.3, state.thickness * 0.3]}>
      <group name="Scene">
        <group name="Sketchfab_model011">
          <group name="Collada_visual_scene_group002">
            <group name="table_lp" />
          </group>
        </group>
        <group name="Sketchfab_model013">
          <group name="25c5b4b3201942cb854d84be0451f0adfbx">
            <group name="RootNode007">
              <group name="Plane_2" />
              <group name="Subdivision_Surface_1" />
              <group name="Table7_obj">
                <group name="Cube_3">
                  <mesh name="Cube_3_default_0" geometry={nodes.Cube_3_default_0.geometry}
                   material={materials['default']} material-color= {state.currentColor}>
       


                    </mesh>
                </group>
                <group name="Cube_3_1">
                  <mesh name="Cube_3_1_default_0" geometry={nodes.Cube_3_1_default_0.geometry} material={materials['default']}>
              
                    </mesh>
                </group>
                <group name="Cube_3_2">
                  <mesh name="Cube_3_2_default_0" geometry={nodes.Cube_3_2_default_0.geometry} 
                  material={materials['default']} >
                    
                    </mesh>
                </group>
                <group name="Disc">
                  <mesh name="Disc_default_0" 
                  geometry={nodes.Disc_default_0.geometry} material={materials['default']} >
                     {state.currentTexture==="Texture1" &&<meshStandardMaterial map={Texture1} roughness={0.8}  />} 
      {state.currentTexture==="Texture2" &&<meshStandardMaterial map={Texture2} roughness={0.8} />} 
       {state.currentTexture==="Texture3" &&<meshStandardMaterial map={Texture3} roughness={0.8} />} 
       {state.currentTexture==="Texture4" &&<meshStandardMaterial map={Texture4} roughness={0.8} />} 
       {state.currentTexture==="Texture5" &&<meshStandardMaterial map={Texture5} roughness={0.8} />} 
       {state.currentTexture==="Texture6" &&<meshStandardMaterial map={Texture6} roughness={0.8} />} 
       {state.currentTexture==="Texture7" &&<meshStandardMaterial map={Texture7} roughness={0.8} />} 
                    </mesh>
                </group>
                <group name="Disc_1">
                  <mesh name="Disc_1_default_0" 
                  geometry={nodes.Disc_1_default_0.geometry} 
                  material={materials['default']} castShadow >
        {state.currentTexture==="Texture1" &&<meshStandardMaterial map={Texture1} roughness={0.8}  />} 
       {state.currentTexture==="Texture2" &&<meshStandardMaterial map={Texture2} roughness={0.8} />} 
       {state.currentTexture==="Texture3" &&<meshStandardMaterial map={Texture3} roughness={0.8} />} 
       {state.currentTexture==="Texture4" &&<meshStandardMaterial map={Texture4} roughness={0.8} />} 
       {state.currentTexture==="Texture5" &&<meshStandardMaterial map={Texture5} roughness={0.8} />} 
       {state.currentTexture==="Texture6" &&<meshStandardMaterial map={Texture6} roughness={0.8} />} 
       {state.currentTexture==="Texture7" &&<meshStandardMaterial map={Texture7} roughness={0.8} />} 
                    </mesh>
                </group>
                <group name="Disc_2">
                  <mesh name="Disc_2_default_0"
                   geometry={nodes.Disc_2_default_0.geometry} material={materials['default']} castShadow>
        {state.currentTexture==="Texture1" &&<meshStandardMaterial map={Texture1} roughness={0.8}  />} 
       {state.currentTexture==="Texture2" &&<meshStandardMaterial map={Texture2} roughness={0.8} />} 
       {state.currentTexture==="Texture3" &&<meshStandardMaterial map={Texture3} roughness={0.8} />} 
       {state.currentTexture==="Texture4" &&<meshStandardMaterial map={Texture4} roughness={0.8} />} 
       {state.currentTexture==="Texture5" &&<meshStandardMaterial map={Texture5} roughness={0.8} />} 
       {state.currentTexture==="Texture6" &&<meshStandardMaterial map={Texture6} roughness={0.8} />} 
       {state.currentTexture==="Texture7" &&<meshStandardMaterial map={Texture7} roughness={0.8} />} 
                    </mesh>
                </group>
                <group name="Symmetry_1">
                  <mesh name="Symmetry_1_default_0" 
                  geometry={nodes.Symmetry_1_default_0.geometry} material={materials['default']} >
                     {state.currentTexture==="Texture1" &&<meshStandardMaterial map={Texture1} roughness={0.8}  />} 
                      {state.currentTexture==="Texture2" &&<meshStandardMaterial map={Texture2} roughness={0.8} />} 
                      {state.currentTexture==="Texture3" &&<meshStandardMaterial map={Texture3} roughness={0.8} />} 
                      {state.currentTexture==="Texture4" &&<meshStandardMaterial map={Texture4} roughness={0.8} />} 
                      {state.currentTexture==="Texture5" &&<meshStandardMaterial map={Texture5} roughness={0.8} />} 
                      {state.currentTexture==="Texture6" &&<meshStandardMaterial map={Texture6} roughness={0.8} />} 
                      {state.currentTexture==="Texture7" &&<meshStandardMaterial map={Texture7} roughness={0.8} />} 
                    </mesh>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/table5.glb')
