/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/Models/bed1.glb --shadow, s 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import state from '@/app/store'
export default function Bed1(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Models/bed1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Object_2001"
         geometry={nodes.Object_2001.geometry} 
         material={materials.material_0}
         material-color = {state.currentColor}
         />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/bed1.glb')
