/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/Models/bed2.glb --shadow, s 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import state from '@/app/store'
export default function Bed2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Models/bed2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} scale={[state.width * 0.5, state.height * 0.5, state.thickness * 0.5]}>
      <group name="Scene">
        <group name="Sketchfab_model014">
          <group name="bedobjcleanermaterialmergergles" />
        </group>
        <group name="Sketchfab_model015">
          <group name="BedFBX">
            <group name="RootNode008">
              <group name="Bed" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model016">
          <group name="Camafbx">
            <group name="RootNode009">
              <group name="Plane001">
                <mesh name="Plane001_Material_0" geometry={nodes.Plane001_Material_0.geometry}
                material-color = {state.currentColor}
                material={materials['Material.001']}
                 />
                <mesh name="Plane001_Material_0001" 
                geometry={nodes.Plane001_Material_0001.geometry} 
                material={materials['Material.001']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/bed2.glb')
